{{- if and .Values.db.enabled (not .Values.db.external.enabled) .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resumelm.fullname" . }}-db
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  {{- include "resumelm.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
