{{- if .Values.imgproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-imgproxy
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: imgproxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: imgproxy
{{- end }}
