{{- if .Values.realtime.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-realtime
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
{{- end }}
