{{- if .Values.redisCommander.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resumelm.fullname" . }}-redis-commander
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "resumelm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis-commander
  template:
    metadata:
      labels:
        {{- include "resumelm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis-commander
    spec:
      {{- include "resumelm.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis-commander
          image: "{{ .Values.redisCommander.image.repository }}:{{ .Values.redisCommander.image.tag }}"
          imagePullPolicy: {{ .Values.redisCommander.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: REDIS_HOSTS
              value: "local:{{ include "resumelm.redisHost" . }}:6379"
          livenessProbe:
            exec:
              command:
                - /redis-commander/bin/healthcheck.js
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /redis-commander/bin/healthcheck.js
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redisCommander.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-redis-commander
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-commander
spec:
  type: {{ .Values.redisCommander.service.type }}
  ports:
    - port: {{ .Values.redisCommander.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis-commander
{{- end }}
