{{- if and .Values.redis.enabled (not .Values.redis.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-redis
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
{{- end }}
