{{- if .Values.rest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-rest
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rest-api
{{- end }}
