{{- if and .Values.storage.enabled .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resumelm.fullname" . }}-storage
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  {{- include "resumelm.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
