{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resumelm.fullname" . }}-storage
  labels:
    {{- include "resumelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resumelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
{{- end }}
